# Generated by Django 4.0.3 on 2022-03-26 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_feilds_table_delete_familymember_delete_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feilds',
            name='tables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprofile.table'),
        ),
    ]
