# Generated by Django 4.0.3 on 2022-03-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_alter_feilds_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feilds',
            name='tables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.table'),
        ),
    ]
